/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FiltersSecurityGroup
 */
public class FiltersSecurityGroupTest {
    private final FiltersSecurityGroup model = new FiltersSecurityGroup();

    /**
     * Model tests for FiltersSecurityGroup
     */
    @Test
    public void testFiltersSecurityGroup() {
        // TODO: test FiltersSecurityGroup
    }

    /**
     * Test the property 'accountIds'
     */
    @Test
    public void accountIdsTest() {
        // TODO: test accountIds
    }

    /**
     * Test the property 'descriptions'
     */
    @Test
    public void descriptionsTest() {
        // TODO: test descriptions
    }

    /**
     * Test the property 'inboundRuleAccountIds'
     */
    @Test
    public void inboundRuleAccountIdsTest() {
        // TODO: test inboundRuleAccountIds
    }

    /**
     * Test the property 'inboundRuleFromPortRanges'
     */
    @Test
    public void inboundRuleFromPortRangesTest() {
        // TODO: test inboundRuleFromPortRanges
    }

    /**
     * Test the property 'inboundRuleIpRanges'
     */
    @Test
    public void inboundRuleIpRangesTest() {
        // TODO: test inboundRuleIpRanges
    }

    /**
     * Test the property 'inboundRuleProtocols'
     */
    @Test
    public void inboundRuleProtocolsTest() {
        // TODO: test inboundRuleProtocols
    }

    /**
     * Test the property 'inboundRuleSecurityGroupIds'
     */
    @Test
    public void inboundRuleSecurityGroupIdsTest() {
        // TODO: test inboundRuleSecurityGroupIds
    }

    /**
     * Test the property 'inboundRuleSecurityGroupNames'
     */
    @Test
    public void inboundRuleSecurityGroupNamesTest() {
        // TODO: test inboundRuleSecurityGroupNames
    }

    /**
     * Test the property 'inboundRuleToPortRanges'
     */
    @Test
    public void inboundRuleToPortRangesTest() {
        // TODO: test inboundRuleToPortRanges
    }

    /**
     * Test the property 'netIds'
     */
    @Test
    public void netIdsTest() {
        // TODO: test netIds
    }

    /**
     * Test the property 'outboundRuleAccountIds'
     */
    @Test
    public void outboundRuleAccountIdsTest() {
        // TODO: test outboundRuleAccountIds
    }

    /**
     * Test the property 'outboundRuleFromPortRanges'
     */
    @Test
    public void outboundRuleFromPortRangesTest() {
        // TODO: test outboundRuleFromPortRanges
    }

    /**
     * Test the property 'outboundRuleIpRanges'
     */
    @Test
    public void outboundRuleIpRangesTest() {
        // TODO: test outboundRuleIpRanges
    }

    /**
     * Test the property 'outboundRuleProtocols'
     */
    @Test
    public void outboundRuleProtocolsTest() {
        // TODO: test outboundRuleProtocols
    }

    /**
     * Test the property 'outboundRuleSecurityGroupIds'
     */
    @Test
    public void outboundRuleSecurityGroupIdsTest() {
        // TODO: test outboundRuleSecurityGroupIds
    }

    /**
     * Test the property 'outboundRuleSecurityGroupNames'
     */
    @Test
    public void outboundRuleSecurityGroupNamesTest() {
        // TODO: test outboundRuleSecurityGroupNames
    }

    /**
     * Test the property 'outboundRuleToPortRanges'
     */
    @Test
    public void outboundRuleToPortRangesTest() {
        // TODO: test outboundRuleToPortRanges
    }

    /**
     * Test the property 'securityGroupIds'
     */
    @Test
    public void securityGroupIdsTest() {
        // TODO: test securityGroupIds
    }

    /**
     * Test the property 'securityGroupNames'
     */
    @Test
    public void securityGroupNamesTest() {
        // TODO: test securityGroupNames
    }

    /**
     * Test the property 'tagKeys'
     */
    @Test
    public void tagKeysTest() {
        // TODO: test tagKeys
    }

    /**
     * Test the property 'tagValues'
     */
    @Test
    public void tagValuesTest() {
        // TODO: test tagValues
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
