/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Phase2Options
 */
public class Phase2OptionsTest {
    private final Phase2Options model = new Phase2Options();

    /**
     * Model tests for Phase2Options
     */
    @Test
    public void testPhase2Options() {
        // TODO: test Phase2Options
    }

    /**
     * Test the property 'phase2DhGroupNumbers'
     */
    @Test
    public void phase2DhGroupNumbersTest() {
        // TODO: test phase2DhGroupNumbers
    }

    /**
     * Test the property 'phase2EncryptionAlgorithms'
     */
    @Test
    public void phase2EncryptionAlgorithmsTest() {
        // TODO: test phase2EncryptionAlgorithms
    }

    /**
     * Test the property 'phase2IntegrityAlgorithms'
     */
    @Test
    public void phase2IntegrityAlgorithmsTest() {
        // TODO: test phase2IntegrityAlgorithms
    }

    /**
     * Test the property 'phase2LifetimeSeconds'
     */
    @Test
    public void phase2LifetimeSecondsTest() {
        // TODO: test phase2LifetimeSeconds
    }

    /**
     * Test the property 'preSharedKey'
     */
    @Test
    public void preSharedKeyTest() {
        // TODO: test preSharedKey
    }

}
