/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Route
 */
public class RouteTest {
    private final Route model = new Route();

    /**
     * Model tests for Route
     */
    @Test
    public void testRoute() {
        // TODO: test Route
    }

    /**
     * Test the property 'creationMethod'
     */
    @Test
    public void creationMethodTest() {
        // TODO: test creationMethod
    }

    /**
     * Test the property 'destinationIpRange'
     */
    @Test
    public void destinationIpRangeTest() {
        // TODO: test destinationIpRange
    }

    /**
     * Test the property 'destinationServiceId'
     */
    @Test
    public void destinationServiceIdTest() {
        // TODO: test destinationServiceId
    }

    /**
     * Test the property 'gatewayId'
     */
    @Test
    public void gatewayIdTest() {
        // TODO: test gatewayId
    }

    /**
     * Test the property 'natServiceId'
     */
    @Test
    public void natServiceIdTest() {
        // TODO: test natServiceId
    }

    /**
     * Test the property 'netAccessPointId'
     */
    @Test
    public void netAccessPointIdTest() {
        // TODO: test netAccessPointId
    }

    /**
     * Test the property 'netPeeringId'
     */
    @Test
    public void netPeeringIdTest() {
        // TODO: test netPeeringId
    }

    /**
     * Test the property 'nicId'
     */
    @Test
    public void nicIdTest() {
        // TODO: test nicId
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'vmAccountId'
     */
    @Test
    public void vmAccountIdTest() {
        // TODO: test vmAccountId
    }

    /**
     * Test the property 'vmId'
     */
    @Test
    public void vmIdTest() {
        // TODO: test vmId
    }

}
