/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.api;

import com.outscale.osc_sdk_java.client.ApiException;
import com.outscale.osc_sdk_java.client.model.CreateSnapshotExportTaskRequest;
import com.outscale.osc_sdk_java.client.model.CreateSnapshotExportTaskResponse;
import com.outscale.osc_sdk_java.client.model.CreateSnapshotRequest;
import com.outscale.osc_sdk_java.client.model.CreateSnapshotResponse;
import com.outscale.osc_sdk_java.client.model.DeleteSnapshotRequest;
import com.outscale.osc_sdk_java.client.model.DeleteSnapshotResponse;
import com.outscale.osc_sdk_java.client.model.ErrorResponse;
import com.outscale.osc_sdk_java.client.model.ReadSnapshotExportTasksRequest;
import com.outscale.osc_sdk_java.client.model.ReadSnapshotExportTasksResponse;
import com.outscale.osc_sdk_java.client.model.ReadSnapshotsRequest;
import com.outscale.osc_sdk_java.client.model.ReadSnapshotsResponse;
import com.outscale.osc_sdk_java.client.model.UpdateSnapshotRequest;
import com.outscale.osc_sdk_java.client.model.UpdateSnapshotResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SnapshotApi
 */
@Ignore
public class SnapshotApiTest {

    private final SnapshotApi api = new SnapshotApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSnapshotTest() throws ApiException {
        CreateSnapshotRequest createSnapshotRequest = null;
        CreateSnapshotResponse response = api.createSnapshot(createSnapshotRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSnapshotExportTaskTest() throws ApiException {
        CreateSnapshotExportTaskRequest createSnapshotExportTaskRequest = null;
        CreateSnapshotExportTaskResponse response = api.createSnapshotExportTask(createSnapshotExportTaskRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSnapshotTest() throws ApiException {
        DeleteSnapshotRequest deleteSnapshotRequest = null;
        DeleteSnapshotResponse response = api.deleteSnapshot(deleteSnapshotRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readSnapshotExportTasksTest() throws ApiException {
        ReadSnapshotExportTasksRequest readSnapshotExportTasksRequest = null;
        ReadSnapshotExportTasksResponse response = api.readSnapshotExportTasks(readSnapshotExportTasksRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readSnapshotsTest() throws ApiException {
        ReadSnapshotsRequest readSnapshotsRequest = null;
        ReadSnapshotsResponse response = api.readSnapshots(readSnapshotsRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSnapshotTest() throws ApiException {
        UpdateSnapshotRequest updateSnapshotRequest = null;
        UpdateSnapshotResponse response = api.updateSnapshot(updateSnapshotRequest);

        // TODO: test validations
    }
    
}
