/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.24
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.outscale.osc_sdk_java.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for CreateVpnConnectionRouteRequest */
public class CreateVpnConnectionRouteRequestTest {
    private final CreateVpnConnectionRouteRequest model = new CreateVpnConnectionRouteRequest();

    /** Model tests for CreateVpnConnectionRouteRequest */
    @Test
    public void testCreateVpnConnectionRouteRequest() {
        // TODO: test CreateVpnConnectionRouteRequest
    }

    /** Test the property 'destinationIpRange' */
    @Test
    public void destinationIpRangeTest() {
        // TODO: test destinationIpRange
    }

    /** Test the property 'dryRun' */
    @Test
    public void dryRunTest() {
        // TODO: test dryRun
    }

    /** Test the property 'vpnConnectionId' */
    @Test
    public void vpnConnectionIdTest() {
        // TODO: test vpnConnectionId
    }
}
