/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Information about the health of a back-end VM.
 */
@ApiModel(description = "Information about the health of a back-end VM.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-01T09:51:28.653202Z[Etc/UTC]")
public class BackendVmHealth {
  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_STATE = "State";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_STATE_REASON = "StateReason";
  @SerializedName(SERIALIZED_NAME_STATE_REASON)
  private String stateReason;

  public static final String SERIALIZED_NAME_VM_ID = "VmId";
  @SerializedName(SERIALIZED_NAME_VM_ID)
  private String vmId;


  public BackendVmHealth description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The description of the state of the back-end VM.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The description of the state of the back-end VM.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public BackendVmHealth state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * The state of the back-end VM (&#x60;InService&#x60; \\| &#x60;OutOfService&#x60; \\| &#x60;Unknown&#x60;).
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The state of the back-end VM (`InService` \\| `OutOfService` \\| `Unknown`).")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public BackendVmHealth stateReason(String stateReason) {
    
    this.stateReason = stateReason;
    return this;
  }

   /**
   * Information about the cause of &#x60;OutOfService&#x60; VMs.&lt;br /&gt; Specifically, whether the cause is Elastic Load Balancing or the VM (&#x60;ELB&#x60; \\| &#x60;Instance&#x60; \\| &#x60;N/A&#x60;).
   * @return stateReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Information about the cause of `OutOfService` VMs.<br /> Specifically, whether the cause is Elastic Load Balancing or the VM (`ELB` \\| `Instance` \\| `N/A`).")

  public String getStateReason() {
    return stateReason;
  }


  public void setStateReason(String stateReason) {
    this.stateReason = stateReason;
  }


  public BackendVmHealth vmId(String vmId) {
    
    this.vmId = vmId;
    return this;
  }

   /**
   * The ID of the back-end VM.
   * @return vmId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the back-end VM.")

  public String getVmId() {
    return vmId;
  }


  public void setVmId(String vmId) {
    this.vmId = vmId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackendVmHealth backendVmHealth = (BackendVmHealth) o;
    return Objects.equals(this.description, backendVmHealth.description) &&
        Objects.equals(this.state, backendVmHealth.state) &&
        Objects.equals(this.stateReason, backendVmHealth.stateReason) &&
        Objects.equals(this.vmId, backendVmHealth.vmId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, state, stateReason, vmId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackendVmHealth {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    stateReason: ").append(toIndentedString(stateReason)).append("\n");
    sb.append("    vmId: ").append(toIndentedString(vmId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

