/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Information about the Client Certificate Authority (CA).
 */
@ApiModel(description = "Information about the Client Certificate Authority (CA).")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-01T09:51:28.653202Z[Etc/UTC]")
public class Ca {
  public static final String SERIALIZED_NAME_CA_FINGERPRINT = "CaFingerprint";
  @SerializedName(SERIALIZED_NAME_CA_FINGERPRINT)
  private String caFingerprint;

  public static final String SERIALIZED_NAME_CA_ID = "CaId";
  @SerializedName(SERIALIZED_NAME_CA_ID)
  private String caId;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;


  public Ca caFingerprint(String caFingerprint) {
    
    this.caFingerprint = caFingerprint;
    return this;
  }

   /**
   * The fingerprint of the CA.
   * @return caFingerprint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fingerprint of the CA.")

  public String getCaFingerprint() {
    return caFingerprint;
  }


  public void setCaFingerprint(String caFingerprint) {
    this.caFingerprint = caFingerprint;
  }


  public Ca caId(String caId) {
    
    this.caId = caId;
    return this;
  }

   /**
   * The ID of the CA.
   * @return caId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the CA.")

  public String getCaId() {
    return caId;
  }


  public void setCaId(String caId) {
    this.caId = caId;
  }


  public Ca description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The description of the CA.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The description of the CA.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ca ca = (Ca) o;
    return Objects.equals(this.caFingerprint, ca.caFingerprint) &&
        Objects.equals(this.caId, ca.caId) &&
        Objects.equals(this.description, ca.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caFingerprint, caId, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ca {\n");
    sb.append("    caFingerprint: ").append(toIndentedString(caFingerprint)).append("\n");
    sb.append("    caId: ").append(toIndentedString(caId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

