/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * One or more filters.
 */
@ApiModel(description = "One or more filters.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-01T09:51:28.653202Z[Etc/UTC]")
public class FiltersCa {
  public static final String SERIALIZED_NAME_CA_FINGERPRINTS = "CaFingerprints";
  @SerializedName(SERIALIZED_NAME_CA_FINGERPRINTS)
  private List<String> caFingerprints = null;

  public static final String SERIALIZED_NAME_CA_IDS = "CaIds";
  @SerializedName(SERIALIZED_NAME_CA_IDS)
  private List<String> caIds = null;

  public static final String SERIALIZED_NAME_DESCRIPTIONS = "Descriptions";
  @SerializedName(SERIALIZED_NAME_DESCRIPTIONS)
  private List<String> descriptions = null;


  public FiltersCa caFingerprints(List<String> caFingerprints) {
    
    this.caFingerprints = caFingerprints;
    return this;
  }

  public FiltersCa addCaFingerprintsItem(String caFingerprintsItem) {
    if (this.caFingerprints == null) {
      this.caFingerprints = new ArrayList<String>();
    }
    this.caFingerprints.add(caFingerprintsItem);
    return this;
  }

   /**
   * The fingerprints of the CAs.
   * @return caFingerprints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fingerprints of the CAs.")

  public List<String> getCaFingerprints() {
    return caFingerprints;
  }


  public void setCaFingerprints(List<String> caFingerprints) {
    this.caFingerprints = caFingerprints;
  }


  public FiltersCa caIds(List<String> caIds) {
    
    this.caIds = caIds;
    return this;
  }

  public FiltersCa addCaIdsItem(String caIdsItem) {
    if (this.caIds == null) {
      this.caIds = new ArrayList<String>();
    }
    this.caIds.add(caIdsItem);
    return this;
  }

   /**
   * The IDs of the CAs.
   * @return caIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The IDs of the CAs.")

  public List<String> getCaIds() {
    return caIds;
  }


  public void setCaIds(List<String> caIds) {
    this.caIds = caIds;
  }


  public FiltersCa descriptions(List<String> descriptions) {
    
    this.descriptions = descriptions;
    return this;
  }

  public FiltersCa addDescriptionsItem(String descriptionsItem) {
    if (this.descriptions == null) {
      this.descriptions = new ArrayList<String>();
    }
    this.descriptions.add(descriptionsItem);
    return this;
  }

   /**
   * The descriptions of the CAs.
   * @return descriptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The descriptions of the CAs.")

  public List<String> getDescriptions() {
    return descriptions;
  }


  public void setDescriptions(List<String> descriptions) {
    this.descriptions = descriptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FiltersCa filtersCa = (FiltersCa) o;
    return Objects.equals(this.caFingerprints, filtersCa.caFingerprints) &&
        Objects.equals(this.caIds, filtersCa.caIds) &&
        Objects.equals(this.descriptions, filtersCa.descriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caFingerprints, caIds, descriptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FiltersCa {\n");
    sb.append("    caFingerprints: ").append(toIndentedString(caFingerprints)).append("\n");
    sb.append("    caIds: ").append(toIndentedString(caIds)).append("\n");
    sb.append("    descriptions: ").append(toIndentedString(descriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

