/*
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.23
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.outscale.osc_sdk_java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.outscale.osc_sdk_java.client.model.PermissionsOnResource;
import com.outscale.osc_sdk_java.client.model.ResourceTag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Information about the snapshot.
 */
@ApiModel(description = "Information about the snapshot.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-01T09:51:28.653202Z[Etc/UTC]")
public class Snapshot {
  public static final String SERIALIZED_NAME_ACCOUNT_ALIAS = "AccountAlias";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ALIAS)
  private String accountAlias;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "AccountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private String accountId;

  public static final String SERIALIZED_NAME_CREATION_DATE = "CreationDate";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  private OffsetDateTime creationDate;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_PERMISSIONS_TO_CREATE_VOLUME = "PermissionsToCreateVolume";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS_TO_CREATE_VOLUME)
  private PermissionsOnResource permissionsToCreateVolume;

  public static final String SERIALIZED_NAME_PROGRESS = "Progress";
  @SerializedName(SERIALIZED_NAME_PROGRESS)
  private Integer progress;

  public static final String SERIALIZED_NAME_SNAPSHOT_ID = "SnapshotId";
  @SerializedName(SERIALIZED_NAME_SNAPSHOT_ID)
  private String snapshotId;

  public static final String SERIALIZED_NAME_STATE = "State";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_TAGS = "Tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<ResourceTag> tags = null;

  public static final String SERIALIZED_NAME_VOLUME_ID = "VolumeId";
  @SerializedName(SERIALIZED_NAME_VOLUME_ID)
  private String volumeId;

  public static final String SERIALIZED_NAME_VOLUME_SIZE = "VolumeSize";
  @SerializedName(SERIALIZED_NAME_VOLUME_SIZE)
  private Integer volumeSize;


  public Snapshot accountAlias(String accountAlias) {
    
    this.accountAlias = accountAlias;
    return this;
  }

   /**
   * The account alias of the owner of the snapshot.
   * @return accountAlias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The account alias of the owner of the snapshot.")

  public String getAccountAlias() {
    return accountAlias;
  }


  public void setAccountAlias(String accountAlias) {
    this.accountAlias = accountAlias;
  }


  public Snapshot accountId(String accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The account ID of the owner of the snapshot.
   * @return accountId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The account ID of the owner of the snapshot.")

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public Snapshot creationDate(OffsetDateTime creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * The date and time of creation of the snapshot.
   * @return creationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of creation of the snapshot.")

  public OffsetDateTime getCreationDate() {
    return creationDate;
  }


  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }


  public Snapshot description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The description of the snapshot.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The description of the snapshot.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Snapshot permissionsToCreateVolume(PermissionsOnResource permissionsToCreateVolume) {
    
    this.permissionsToCreateVolume = permissionsToCreateVolume;
    return this;
  }

   /**
   * Get permissionsToCreateVolume
   * @return permissionsToCreateVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PermissionsOnResource getPermissionsToCreateVolume() {
    return permissionsToCreateVolume;
  }


  public void setPermissionsToCreateVolume(PermissionsOnResource permissionsToCreateVolume) {
    this.permissionsToCreateVolume = permissionsToCreateVolume;
  }


  public Snapshot progress(Integer progress) {
    
    this.progress = progress;
    return this;
  }

   /**
   * The progress of the snapshot, as a percentage.
   * @return progress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The progress of the snapshot, as a percentage.")

  public Integer getProgress() {
    return progress;
  }


  public void setProgress(Integer progress) {
    this.progress = progress;
  }


  public Snapshot snapshotId(String snapshotId) {
    
    this.snapshotId = snapshotId;
    return this;
  }

   /**
   * The ID of the snapshot.
   * @return snapshotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the snapshot.")

  public String getSnapshotId() {
    return snapshotId;
  }


  public void setSnapshotId(String snapshotId) {
    this.snapshotId = snapshotId;
  }


  public Snapshot state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * The state of the snapshot (&#x60;in-queue&#x60; \\| &#x60;completed&#x60; \\| &#x60;error&#x60;).
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The state of the snapshot (`in-queue` \\| `completed` \\| `error`).")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public Snapshot tags(List<ResourceTag> tags) {
    
    this.tags = tags;
    return this;
  }

  public Snapshot addTagsItem(ResourceTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<ResourceTag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * One or more tags associated with the snapshot.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "One or more tags associated with the snapshot.")

  public List<ResourceTag> getTags() {
    return tags;
  }


  public void setTags(List<ResourceTag> tags) {
    this.tags = tags;
  }


  public Snapshot volumeId(String volumeId) {
    
    this.volumeId = volumeId;
    return this;
  }

   /**
   * The ID of the volume used to create the snapshot.
   * @return volumeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the volume used to create the snapshot.")

  public String getVolumeId() {
    return volumeId;
  }


  public void setVolumeId(String volumeId) {
    this.volumeId = volumeId;
  }


  public Snapshot volumeSize(Integer volumeSize) {
    
    this.volumeSize = volumeSize;
    return this;
  }

   /**
   * The size of the volume used to create the snapshot, in gibibytes (GiB).
   * @return volumeSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The size of the volume used to create the snapshot, in gibibytes (GiB).")

  public Integer getVolumeSize() {
    return volumeSize;
  }


  public void setVolumeSize(Integer volumeSize) {
    this.volumeSize = volumeSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Snapshot snapshot = (Snapshot) o;
    return Objects.equals(this.accountAlias, snapshot.accountAlias) &&
        Objects.equals(this.accountId, snapshot.accountId) &&
        Objects.equals(this.creationDate, snapshot.creationDate) &&
        Objects.equals(this.description, snapshot.description) &&
        Objects.equals(this.permissionsToCreateVolume, snapshot.permissionsToCreateVolume) &&
        Objects.equals(this.progress, snapshot.progress) &&
        Objects.equals(this.snapshotId, snapshot.snapshotId) &&
        Objects.equals(this.state, snapshot.state) &&
        Objects.equals(this.tags, snapshot.tags) &&
        Objects.equals(this.volumeId, snapshot.volumeId) &&
        Objects.equals(this.volumeSize, snapshot.volumeSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountAlias, accountId, creationDate, description, permissionsToCreateVolume, progress, snapshotId, state, tags, volumeId, volumeSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Snapshot {\n");
    sb.append("    accountAlias: ").append(toIndentedString(accountAlias)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    permissionsToCreateVolume: ").append(toIndentedString(permissionsToCreateVolume)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    snapshotId: ").append(toIndentedString(snapshotId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    volumeId: ").append(toIndentedString(volumeId)).append("\n");
    sb.append("    volumeSize: ").append(toIndentedString(volumeSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

